### ISSUE TITLE
Achtung bei der Benennung von "id" und "class": htmllint verlangt Format "underscore"

### ISSUE THREAD

**Issue by FischeChrist** [hauserulrich/FS19_IW15tz_Zuerich_DGUI#6]
Achtung bei der Benennung von "id" und "class": htmllint verlangt diese im Format "underscore"! CamelCase führt zu einem Error beim Test mit TravisCI.

JA:  "underscore": Lowercase and underscore-separated.
NEIN: "camel": camelCase (or CamelCase).

Quelle der Formate: https://github.com/htmllint/htmllint/wiki/Options

**Comment by FischeChrist** [comment]
Problem bei der Benennung von classes, die auf Bootstrap CDN zugreifen.
Diese sind zum Beispiel benannt mit class="btn btn-primary", class="btn btn-secondary rounded-circle", etc. Diese validiert Travis CI aktuell nicht, sondern zeigt einen Error an.

Dieser sieht zum Beispiel so aus: 
./www/html/index.html: line 86, col 14, class value must match the format: underscore

Wie können wir das Problem lösen?

**Comment by hauserulrich** [comment]
Umgestellt auf BEM, funktioniert gut mit Kleinbuchstaben und Bindestrich. Arbeitet deshalb auch gut mit Bootstrap-Klassenbenennungen zusammen.
