### ISSUE TITLE
Verstehe Error nicht, Dokumentation von htmllint hilft nicht weiter

### ISSUE THREAD

**Issue by FischeChrist** [hauserulrich/FS19_IW15tz_Zuerich_DGUI#7]
Wir haben einen Error beim Validieren:
0.40s$ ./node_modules/.bin/htmllint ./www/**/*.html
./www/html/index.html: line 132, col 7, line ending does not match format: lf

Zeile 132 ist die letzte Zeile im HTML-Dokument, col 7 ist das letzte Zeichen, ein ">". Danach kommt nichts mehr. 

Die Dokumentation sagt folgendes:

line-end-style

Default: "lf"
Line endings must conform to the given style.

    "lf": Unix style, ending in LF.

Quelle: https://github.com/htmllint/htmllint/wiki/Options#line-end-style

Ich verstehe nicht, was ich hier anders machen soll?

**Comment by hauserulrich** [comment]
Der Linter verlangt, dass am Ende der Datei noch eine (leere) neue Zeile steht.
