### ISSUE TITLE
Info: Bei Hex-Code für Farben NICHT Grossbuchstaben verwenden

### ISSUE THREAD

**Issue by FischeChrist** [hauserulrich/FS19_IW15tz_Zuerich_DGUI#8]
Hallo,

bei Farben in CSS nur Kleinbuchstaben, sonst validiert euch das Travis CI nicht:

 22:14  ✖  Expected "#3B5998" to be          color-hex-case                    
           "#3b5998"                                                                                          
 27:25  ✖  Expected "#55ACEE" to be          color-hex-case                    
           "#55acee"

**Comment by hauserulrich** [comment]
Am besten mit rgb(r, g, b) arbeiten
