### ISSUE TITLE
Probleme mit Hex-Werten?

### ISSUE THREAD

**Issue by FischeChrist** [hauserulrich/FS19_IW15tz_Zuerich_DGUI#9]
Es tritt ein Fehler beim Validieren auf, den ich nicht lösen kann. Internet und Dokumentation helfen nicht. Hat jemand eine Lösung?

Fehler:
www/style/main.css
 26:13  ✖  Unexpected hex color "#3b5998"    color-no-hex                 
 32:13  ✖  Unexpected hex color "#55acee"    color-no-hex              

CSS:

.fa-facebook
{
	background: #3b5998;
	color: white;
}

.fa-twitter
{
	background: #55acee;
	color: white;
}

**Comment by hauserulrich** [comment]
https://stylelint.io/user-guide/rules/color-no-hex/ erkärt, was falsch ist. Der Linter ist im default darauf eingestellt, hex nicht zu tolerieren. Wenn Sie das wünschen, kann das geändert werden.
